### ISSUE TITLE
Reuse minikube podman

### ISSUE THREAD

**Issue by JMesens** [boot2podman/machine#20]
In my setup I have no local docker daemon and a minikube running in virtualbox on mac.
On the minikube podman is working fine. (minikube ssh)
Now I was trying to use podman's PODMAN_VARLINK_BRIDGE to connect to the minikube podman.

This would be nice that I could do podman build and the actual build would be done in virtualbox so that the image is also available for minikube to use.

**Comment by afbjorklund** [comment]
I made the decision to not bother with varlink for the minikube image, but I suppose that could be revisited. Originally I was a bit concerned about the root requirement for ssh, but now works with sudo.

If I remember correctly, what needs to be done is to install the `varlink` binary (for the bridge), and to install the socket-activated for systemd. Optionally deploy a resolver,* but everyone ignores that...

* /etc/systemd/system/io.podman.socket

* /etc/systemd/system/io.podman.service

Could you open an issue over at [minikube](https://github.com/kubernetes/minikube), instead ?

I don't think that this will require any changes to libmachine.

----

(*) The resolver allows you to say `io.podman`, instead of hardcoding the socket path.

```console
$ sudo varlink resolve io.podman
unix:/run/podman/io.podman;mode=0600
```

The downside is of course that you have to hardcode `/run/org.varlink.resolver` instead...

So as long as podman is the only thing in the world that uses varlink, it's not really a win.

**Comment by afbjorklund** [comment]
Packaged `varlink` for minikube at https://github.com/kubernetes/minikube/compare/master...afbjorklund:varlink

I think the systemd socket/service are available from podman's `make install.systemd`

**Comment by afbjorklund** [comment]
The varlink support is being **removed** upstream, so I think that I will continue with using ssh.

https://podman.io/releases/2020/01/17/podman-new-api.html

**Comment by afbjorklund** [comment]
Using the systemd units requires ssh as root, so better to use the varlink bridge after all...

The command to run is: `sudo varlink -A \'podman varlink \$VARLINK_ADDRESS\' bridge`

**Comment by afbjorklund** [comment]
See https://github.com/kubernetes/minikube/issues/6350
